package entities;
// Generated Nov 2, 2016 10:23:53 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * AircraftManufacturer generated by hbm2java
 */
@Entity
@Table(name = "aircraft_manufacturer", catalog = "booking_project")
public class AircraftManufacturer implements java.io.Serializable {

	private String manufacturerId;
	private String manufacturerName;
	private String description;

	public AircraftManufacturer() {
	}

	public AircraftManufacturer(String manufacturerId) {
		this.manufacturerId = manufacturerId;
	}

	public AircraftManufacturer(String manufacturerId, String manufacturerName, String description) {
		this.manufacturerId = manufacturerId;
		this.manufacturerName = manufacturerName;
		this.description = description;
	}

	@Id

	@Column(name = "manufacturer_id", unique = true, nullable = false, length = 50)
	public String getManufacturerId() {
		return this.manufacturerId;
	}

	public void setManufacturerId(String manufacturerId) {
		this.manufacturerId = manufacturerId;
	}

	@Column(name = "manufacturer_name", length = 50)
	public String getManufacturerName() {
		return this.manufacturerName;
	}

	public void setManufacturerName(String manufacturerName) {
		this.manufacturerName = manufacturerName;
	}

	@Column(name = "description", length = 65535)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
