package entities;
// Generated Nov 2, 2016 10:23:53 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * AircraftSeat generated by hbm2java
 */
@Entity
@Table(name = "aircraft_seat", catalog = "booking_project")
public class AircraftSeat implements java.io.Serializable {

	private String seatId;
	private String aircraftId;
	private String class_;

	public AircraftSeat() {
	}

	public AircraftSeat(String seatId) {
		this.seatId = seatId;
	}

	public AircraftSeat(String seatId, String aircraftId, String class_) {
		this.seatId = seatId;
		this.aircraftId = aircraftId;
		this.class_ = class_;
	}

	@Id

	@Column(name = "seat_id", unique = true, nullable = false, length = 50)
	public String getSeatId() {
		return this.seatId;
	}

	public void setSeatId(String seatId) {
		this.seatId = seatId;
	}

	@Column(name = "aircraft_id", length = 50)
	public String getAircraftId() {
		return this.aircraftId;
	}

	public void setAircraftId(String aircraftId) {
		this.aircraftId = aircraftId;
	}

	@Column(name = "class", length = 10)
	public String getClass_() {
		return this.class_;
	}

	public void setClass_(String class_) {
		this.class_ = class_;
	}

}
