package entities;
// Generated Nov 2, 2016 10:23:53 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Aircraft generated by hbm2java
 */
@Entity
@Table(name = "aircraft", catalog = "booking_project")
public class Aircraft implements java.io.Serializable {

	private String aircraftId;
	private String manufacturerId;
	private String model;

	public Aircraft() {
	}

	public Aircraft(String aircraftId) {
		this.aircraftId = aircraftId;
	}

	public Aircraft(String aircraftId, String manufacturerId, String model) {
		this.aircraftId = aircraftId;
		this.manufacturerId = manufacturerId;
		this.model = model;
	}

	@Id

	@Column(name = "aircraft_id", unique = true, nullable = false, length = 50)
	public String getAircraftId() {
		return this.aircraftId;
	}

	public void setAircraftId(String aircraftId) {
		this.aircraftId = aircraftId;
	}

	@Column(name = "manufacturer_id", length = 50)
	public String getManufacturerId() {
		return this.manufacturerId;
	}

	public void setManufacturerId(String manufacturerId) {
		this.manufacturerId = manufacturerId;
	}

	@Column(name = "model", length = 50)
	public String getModel() {
		return this.model;
	}

	public void setModel(String model) {
		this.model = model;
	}

}
