package entities;
// Generated Nov 2, 2016 10:23:53 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Booking generated by hbm2java
 */
@Entity
@Table(name = "booking", catalog = "booking_project")
public class Booking implements java.io.Serializable {

	private String bookingId;
	private String unregisteredName;
	private String registeredName;
	private Integer phone;
	private String email;
	private String passengersName;
	private String passengersSurname;
	private String passengersSex;
	private Date passengersDob;
	private String passengerCategories;
	private String citizenship;
	private String passport;
	private String identityCard;

	public Booking() {
	}

	public Booking(String bookingId) {
		this.bookingId = bookingId;
	}

	public Booking(String bookingId, String unregisteredName, String registeredName, Integer phone, String email,
			String passengersName, String passengersSurname, String passengersSex, Date passengersDob,
			String passengerCategories, String citizenship, String passport, String identityCard) {
		this.bookingId = bookingId;
		this.unregisteredName = unregisteredName;
		this.registeredName = registeredName;
		this.phone = phone;
		this.email = email;
		this.passengersName = passengersName;
		this.passengersSurname = passengersSurname;
		this.passengersSex = passengersSex;
		this.passengersDob = passengersDob;
		this.passengerCategories = passengerCategories;
		this.citizenship = citizenship;
		this.passport = passport;
		this.identityCard = identityCard;
	}

	@Id

	@Column(name = "booking_id", unique = true, nullable = false, length = 50)
	public String getBookingId() {
		return this.bookingId;
	}

	public void setBookingId(String bookingId) {
		this.bookingId = bookingId;
	}

	@Column(name = "unregistered_name", length = 50)
	public String getUnregisteredName() {
		return this.unregisteredName;
	}

	public void setUnregisteredName(String unregisteredName) {
		this.unregisteredName = unregisteredName;
	}

	@Column(name = "registered_name", length = 50)
	public String getRegisteredName() {
		return this.registeredName;
	}

	public void setRegisteredName(String registeredName) {
		this.registeredName = registeredName;
	}

	@Column(name = "phone")
	public Integer getPhone() {
		return this.phone;
	}

	public void setPhone(Integer phone) {
		this.phone = phone;
	}

	@Column(name = "email", length = 50)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "passengers_name", length = 50)
	public String getPassengersName() {
		return this.passengersName;
	}

	public void setPassengersName(String passengersName) {
		this.passengersName = passengersName;
	}

	@Column(name = "passengers_surname", length = 50)
	public String getPassengersSurname() {
		return this.passengersSurname;
	}

	public void setPassengersSurname(String passengersSurname) {
		this.passengersSurname = passengersSurname;
	}

	@Column(name = "passengers_sex", length = 5)
	public String getPassengersSex() {
		return this.passengersSex;
	}

	public void setPassengersSex(String passengersSex) {
		this.passengersSex = passengersSex;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "passengers_dob", length = 19)
	public Date getPassengersDob() {
		return this.passengersDob;
	}

	public void setPassengersDob(Date passengersDob) {
		this.passengersDob = passengersDob;
	}

	@Column(name = "passenger_categories", length = 10)
	public String getPassengerCategories() {
		return this.passengerCategories;
	}

	public void setPassengerCategories(String passengerCategories) {
		this.passengerCategories = passengerCategories;
	}

	@Column(name = "citizenship", length = 45)
	public String getCitizenship() {
		return this.citizenship;
	}

	public void setCitizenship(String citizenship) {
		this.citizenship = citizenship;
	}

	@Column(name = "passport", length = 45)
	public String getPassport() {
		return this.passport;
	}

	public void setPassport(String passport) {
		this.passport = passport;
	}

	@Column(name = "identity_card", length = 45)
	public String getIdentityCard() {
		return this.identityCard;
	}

	public void setIdentityCard(String identityCard) {
		this.identityCard = identityCard;
	}

}
