package entities;
// Generated Nov 2, 2016 10:23:53 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DirectionId generated by hbm2java
 */
@Embeddable
public class DirectionId implements java.io.Serializable {

	private String originId;
	private String destinationId;

	public DirectionId() {
	}

	public DirectionId(String originId, String destinationId) {
		this.originId = originId;
		this.destinationId = destinationId;
	}

	@Column(name = "origin_id", nullable = false, length = 10)
	public String getOriginId() {
		return this.originId;
	}

	public void setOriginId(String originId) {
		this.originId = originId;
	}

	@Column(name = "destination_id", nullable = false, length = 10)
	public String getDestinationId() {
		return this.destinationId;
	}

	public void setDestinationId(String destinationId) {
		this.destinationId = destinationId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DirectionId))
			return false;
		DirectionId castOther = (DirectionId) other;

		return ((this.getOriginId() == castOther.getOriginId()) || (this.getOriginId() != null
				&& castOther.getOriginId() != null && this.getOriginId().equals(castOther.getOriginId())))
				&& ((this.getDestinationId() == castOther.getDestinationId())
						|| (this.getDestinationId() != null && castOther.getDestinationId() != null
								&& this.getDestinationId().equals(castOther.getDestinationId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getOriginId() == null ? 0 : this.getOriginId().hashCode());
		result = 37 * result + (getDestinationId() == null ? 0 : this.getDestinationId().hashCode());
		return result;
	}

}
