package entities;
// Generated Nov 2, 2016 10:23:53 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Direction generated by hbm2java
 */
@Entity
@Table(name = "direction", catalog = "booking_project")
public class Direction implements java.io.Serializable {

	private DirectionId id;

	public Direction() {
	}

	public Direction(DirectionId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "originId", column = @Column(name = "origin_id", nullable = false, length = 10)),
			@AttributeOverride(name = "destinationId", column = @Column(name = "destination_id", nullable = false, length = 10)) })
	public DirectionId getId() {
		return this.id;
	}

	public void setId(DirectionId id) {
		this.id = id;
	}

}
