package entities;
// Generated Nov 2, 2016 10:23:53 PM by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Flight generated by hbm2java
 */
@Entity
@Table(name = "flight", catalog = "booking_project")
public class Flight implements java.io.Serializable {

	private FlightId id;
	private String limitBaggageWeight;
	private BigDecimal totalFee;

	public Flight() {
	}

	public Flight(FlightId id) {
		this.id = id;
	}

	public Flight(FlightId id, String limitBaggageWeight, BigDecimal totalFee) {
		this.id = id;
		this.limitBaggageWeight = limitBaggageWeight;
		this.totalFee = totalFee;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "flightId", column = @Column(name = "flight_id", nullable = false, length = 50)),
			@AttributeOverride(name = "flightScheduleId", column = @Column(name = "flight_schedule_id", nullable = false, length = 45)),
			@AttributeOverride(name = "seatId", column = @Column(name = "seat_id", nullable = false, length = 45)) })
	public FlightId getId() {
		return this.id;
	}

	public void setId(FlightId id) {
		this.id = id;
	}

	@Column(name = "limit_baggage_weight", length = 45)
	public String getLimitBaggageWeight() {
		return this.limitBaggageWeight;
	}

	public void setLimitBaggageWeight(String limitBaggageWeight) {
		this.limitBaggageWeight = limitBaggageWeight;
	}

	@Column(name = "total_fee", precision = 14, scale = 4)
	public BigDecimal getTotalFee() {
		return this.totalFee;
	}

	public void setTotalFee(BigDecimal totalFee) {
		this.totalFee = totalFee;
	}

}
