package entities;
// Generated Nov 2, 2016 10:23:53 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * FlightId generated by hbm2java
 */
@Embeddable
public class FlightId implements java.io.Serializable {

	private String flightId;
	private String flightScheduleId;
	private String seatId;

	public FlightId() {
	}

	public FlightId(String flightId, String flightScheduleId, String seatId) {
		this.flightId = flightId;
		this.flightScheduleId = flightScheduleId;
		this.seatId = seatId;
	}

	@Column(name = "flight_id", nullable = false, length = 50)
	public String getFlightId() {
		return this.flightId;
	}

	public void setFlightId(String flightId) {
		this.flightId = flightId;
	}

	@Column(name = "flight_schedule_id", nullable = false, length = 45)
	public String getFlightScheduleId() {
		return this.flightScheduleId;
	}

	public void setFlightScheduleId(String flightScheduleId) {
		this.flightScheduleId = flightScheduleId;
	}

	@Column(name = "seat_id", nullable = false, length = 45)
	public String getSeatId() {
		return this.seatId;
	}

	public void setSeatId(String seatId) {
		this.seatId = seatId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof FlightId))
			return false;
		FlightId castOther = (FlightId) other;

		return ((this.getFlightId() == castOther.getFlightId()) || (this.getFlightId() != null
				&& castOther.getFlightId() != null && this.getFlightId().equals(castOther.getFlightId())))
				&& ((this.getFlightScheduleId() == castOther.getFlightScheduleId())
						|| (this.getFlightScheduleId() != null && castOther.getFlightScheduleId() != null
								&& this.getFlightScheduleId().equals(castOther.getFlightScheduleId())))
				&& ((this.getSeatId() == castOther.getSeatId()) || (this.getSeatId() != null
						&& castOther.getSeatId() != null && this.getSeatId().equals(castOther.getSeatId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getFlightId() == null ? 0 : this.getFlightId().hashCode());
		result = 37 * result + (getFlightScheduleId() == null ? 0 : this.getFlightScheduleId().hashCode());
		result = 37 * result + (getSeatId() == null ? 0 : this.getSeatId().hashCode());
		return result;
	}

}
