package entities;
// Generated Nov 2, 2016 10:23:53 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TransactionId generated by hbm2java
 */
@Embeddable
public class TransactionId implements java.io.Serializable {

	private int paymentId;
	private String bookingId;

	public TransactionId() {
	}

	public TransactionId(int paymentId, String bookingId) {
		this.paymentId = paymentId;
		this.bookingId = bookingId;
	}

	@Column(name = "payment_id", nullable = false)
	public int getPaymentId() {
		return this.paymentId;
	}

	public void setPaymentId(int paymentId) {
		this.paymentId = paymentId;
	}

	@Column(name = "booking_id", nullable = false, length = 45)
	public String getBookingId() {
		return this.bookingId;
	}

	public void setBookingId(String bookingId) {
		this.bookingId = bookingId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TransactionId))
			return false;
		TransactionId castOther = (TransactionId) other;

		return (this.getPaymentId() == castOther.getPaymentId())
				&& ((this.getBookingId() == castOther.getBookingId()) || (this.getBookingId() != null
						&& castOther.getBookingId() != null && this.getBookingId().equals(castOther.getBookingId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getPaymentId();
		result = 37 * result + (getBookingId() == null ? 0 : this.getBookingId().hashCode());
		return result;
	}

}
